version: '3.8'

services:
  network-handler: 
    build: ./networkHandler
    volumes:
      - type: bind
        source: ./networkHandler/networkHandlerPipe
        target: /networkHandlerPipe
    ports:
      - 5001:5001
    networks:
      - yg
  web-server:
    build: ./webServer
    ports: 
      - 5000
    depends_on: 
      - network-handler
    links:
      - network-handler
    networks:
      - yg

networks:
  yg: